### ISSUE TITLE
Wireless network 5GHZ can be turned on.

### ISSUE THREAD

**Issue by belliel** [mountaser/Moun_Kernel_Tissot#10]
The file net/wireless/db.txt should be kept up-to-date with the db.txt file available in the git repository here:
git://git.kernel.org/pub/scm/linux/kernel/git/linville/wireless-regdb.git

In several regions 5GHZ can work, but you use old db.txt file, so in "5GHZ wifi working" regions 5GHZ turned off

**Comment by mountaser** [comment]
well thanks for the info xD i will make sure to merge that next update.... that i have no idea when it is going to be xD
